downstream_dependencies: 
  - wc_sim
email_notifications: 
  - jonrkarr@gmail.com
  - arthur.p.goldberg@mssm.edu
static_analyses:
  ignore_files: []
  ignore_unused_requirements:
    - pympler
  ignore_missing_requirements:
    - configobj