""" Setup simulation example configuration

:Author: Arthur Goldberg <Arthur.Goldberg@mssm.edu>
:Date: 2016-10-03
:Copyright: 2016-2020, Karr Lab
:License: MIT
"""

import warnings

from .config import core
from wc_utils.debug_logs.core import DebugLogsManager

# setup debug logs
config = core.get_debug_logs_config()
with warnings.catch_warnings():
    # Ignore RuntimeWarning warnings in codecs that are generated by logging2.FileHandler() calls
    # logging2 is an archived repo
    warnings.filterwarnings("ignore",
                            category=RuntimeWarning,
                            module='codecs')
    logs = DebugLogsManager().setup_logs(config)
